### ISSUE TITLE
Fix test failures

### ISSUE THREAD

**Issue by kortemik** [teragrep/jos_01#10]
**Description**
There are test failures. They exist perhaps because containers on github use different linux version. Please adjust the objects so that they are kernel version aware and use appropriate object to extract the information.

Following tests fail:
```
Error:  com.teragrep.jos_01.procfs.LinuxOSTest.cpuInfoTest -- Time elapsed: 0.011 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: java.lang.Exception: Failed to calculate system CPU thread count!
```

```
Error:    LinuxOSTest.highLevelMethodsTest:240 Unexpected exception thrown: java.lang.Exception: Failed to calculate system CPU count!
```

```
Error:  com.teragrep.jos_01.procfs.ProcessTest.timestampTest -- Time elapsed: 0.003 s <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
```

**Comment by Laukkala** [comment]
Looks like the error is caused due to an unexpected number of fields being present within /proc/cpuinfo.
I think different distributions and versions can have a higher or lower number of fields present than others.

Maybe CPUInfo should be reworked to check that the field's name corresponds to the value we are expecting to see to avoid issues with unexpected fields

**Comment by kortemik** [comment]
after merging #11 following are still failing:
```
Error:  Failures: 
Error:    ProcessTest.timestampTest:302 Unexpected exception thrown: org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
Error:    TaskTest.timestampTest:140 Unexpected exception thrown: org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
```
